services:
  apisix:
    image: apache/apisix
    ports:
      - "9080:9080"    # HTTP endpoint
      - "9180:9180"    # Admin-API
    volumes:
      - ./docker/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    environment:
      - ENABLE_ADMIN=true
      - ADMIN_KEY=supersecret
    networks:
      - intranet
  etcd:
    image: bitnamilegacy/etcd:3.6
    restart: always
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - intranet
  apisix-dashboard:
    image: apache/apisix-dashboard
    depends_on:
      - apisix
    ports:
      - "9000:9000"
    volumes:
      - ./docker/apisix_dashboard_conf/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    environment:
      - DEFAULT_APISIX_ADMIN_KEY=supersecret
      - APISIX_LISTEN_ADDRESS=http://apisix:9091
    networks:
      - intranet
networks:
  intranet:
    external: true