apisix:
  node_listen: 9080
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: supersecret
        role: admin

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30